# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    habitacio_directory_gallery: '%kernel.project_dir%/public/images/habitaciones'
    event_directory_gallery: '%kernel.project_dir%/public/images/events'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    dwes.bll.baseBLL:
        class: App\BLL\BaseBLL
        abstract: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@validator'
    dwes.bll.ImagenBLL:
        class: App\BLL\HabitacioBLL
        parent: dwes.bll.baseBLL
        calls:
            - setRequestStack: ['@Symfony\Component\HttpFoundation\RequestStack']
            - setSecurity: ['@Symfony\Component\Security\Core\Security']